### PR TITLE
fix: don’t attempt to call prop.get() when prop is nullish

### LINKED ISSUE #24: Can't pick DataArray + SliceRepresentation
Hi, I enabled picking for my View (`pickingModes={['click']} onClick={selection => console.log(selection)}`) and it works correctly, but as soon I click on a `SliceRepresentation` linked to a `DataArray` element I get the following error:

CleanShot 2021-08-01 at 11 20 56@2x

It looks like that here `prop` is undefined:

https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js#L514

### PR DESCRIPTION
**Pull request by FezVrasta**
fixes #24

### CODE REVIEW

File: src/core/View.js [hunk 1]
```diff
@@ -511,6 +511,9 @@ export default class View extends Component {
       return this.selections.map((v) => {
         const { prop, compositeID, displayPosition } = v.getProperties();
 
+        // Return false to mark this item for removal
+        if (prop == null) return false;
```
Comment (jourdain) [inline src/core/View.js:515]: Should we write `if (!prop) { return false; }` instead?

File: src/core/View.js [hunk 2]
```diff
@@ -493,7 +493,7 @@ export default class View extends Component {
         const representationIds = [];
         this.selections.forEach((v) => {
           const { prop } = v.getProperties();
-          const { representationId } = prop.get('representationId');
+          const representationId = prop?.get('representationId').representationId;
```
Comment (FezVrasta) [inline src/core/View.js:496]: I'm not sure if your build pipeline supports the optional chaining operator, I can replace it with something else if not.

**Comment by jourdain** [comment]
Thanks, does that solve your issue?

Can you rename your commit like `fix(View): Prevent invalid access when picking`

File: src/core/View.js (hunk 2 above)
Comment (jourdain) [reply src/core/View.js:496]: Not sure either.

File: src/core/View.js (hunk 1 above)
Comment (FezVrasta) [reply src/core/View.js:515]: I'm used to `== null` because it's the quickest way to check for `null` and `undefined` while not checking for any other falsy value, I know in this case it will always be either an object-type or null/undefined so it's not strictly needed, i't just clearer to me. (I come from a strict Flow-type checking background, sorry 😬)

**Comment by FezVrasta** [comment]
> Thanks, does that solve your issue?

Yes it works indeed

File: src/core/View.js (hunk 2 above)
Comment (FezVrasta) [reply src/core/View.js:496]: It is, I just checked the `dist` output.

**Comment by jourdain** [comment]
Thanks for your contribution!
